# Use root/example as user/password credentials
version: '3.3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/subu/mongo-data/docker:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      lnet:
        ipv4_address: 172.28.0.2


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      lnet:
        ipv4_address: 172.28.0.3

networks:
  lnet:
    ipam:
      config:
        - subnet: 172.28.0.0/16
      